config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'contacts/new'

  get 'contacts/create'

  get 'application/privacy' => 'application#privacy'

  get 'application/about_us' => 'application#about_us'

  get 'user/new' => 'users#new'

  get 'user/show' => 'users#show'

  post 'user/new' => 'users#create'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'
  
  get '/logout' => 'sessions#destroy'

  get 'bills/show', as: :credit_bill  

  get 'bills/index', as: :bills   

  post 'likes/create', as: :like 

  scope '(:locale)' do 
    resources :products do  
    resources :comments 
      end
    resources :orders
    resources :contacts
    resources :line_items
    resources :carts
    root 'products#index', as: 'Products', via: :all
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	has_one :user

	def add_product(product_id)
		# current_item = line_items.find_by(product_id: product_id)
		current_item = nil
        line_items.each { |item| current_item = item if item.product_id == product_id } 
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end

	def total_price
  		line_items.to_a.sum { |item| item.total_price}
 	end
end

app/models/comment.rb
 class Comment < ActiveRecord::Base
   belongs_to :product
   belongs_to :user
 end 

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, :email, :message, presence: true

end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/line_item.rb
 class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
  	product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
 has_many :line_items, dependent: :destroy
 
 PAYMENT_TYPES = [ "Check", "Credit card", "Purchase Order"]
 
 validates :name, :address, :email, presence: true
 validates :pay_type, inclusion: PAYMENT_TYPES

 def add_line_items_from_cart(cart)
	cart.line_items.each do |item|	
	   item.cart_id = nil
	   line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :comments
  has_one :like
  before_destroy :ensure_no_referenced_by_any_line_item
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, :isbn, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

  def self.latest
    Product.order(:updated_at).last
  end

  def self.search(search)
    where("title LIKE ?", "%#{search}%") 
  end

  def self.search_by_category(search)
     where("category LIKE ?", "%#{search}%") 
  end

  private

  def ensure_no_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :cart
  has_many :comments
  has_one :like
  has_secure_password 
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
 	include CurrentCart
	
  def index
   	@order = Order.find(params[:id])
   end

   def show 
   	 @order = Order.find(params[:id])
   end
 end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == current_user.cart_id
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to acess invalid cart #{params[:id]}"
      redirect_to products_url, notice: 'Invalid cart'
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  before_action :set_cart , only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:index]


  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/new
  def new
    if @cart.line_items.empty?
      redirect_to products_url, notice: "Your cart is empty"
      return
    end
    
    @order = Order.new
  end
  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)
    respond_to do |format|
      if @order.save
        if @order.pay_type == 'Credit card'
          format.html { redirect_to credit_bill_path(id: @order.id) }
        else 
           format.html { redirect_to bills_url(id: @order.id), notice: 'Thank you for your order.' }
           format.json { render :show, status: :created, location: @order }
         end
         OrderNotifier.received(@order).deliver
      else
          format.html { render :new }
          format.json { render json: @order.errors, status: :unprocessable_entity }
       end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper

end

app/helpers/carts_helper.rb
module CartsHelper
	def format_qty_value(number)
		number = number.to_i
		pluralize(number, 'item')
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def liked(id_param, product_id)
    if Like.find_by_user_id_and_product_id(id_param, product_id).nil? 
      false
    else
      Like.find_by_user_id_and_product_id(id_param, product_id).user_id == current_user.id 
    end    
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orders/_form.html.erb
<div id = "body_new-user" class="container-fluid">
 <header >
  <div align="center"><h1> <%= t('.checkout')%> </h1></div>
</header>       
<div  class="form">
  <%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

        <ul>
        <% @order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <p class="contact"><label> <%= t('.name') %> </label></p>
    <%= f.text_field :name, id: 'name', placeholder: t('.first_and_last_name') %>

    <p class="contact"><label> <%= t('.email') %> </label></p>
    <%= f.email_field :email, id: 'email', placeholder: t('.email2')%>

    <p class="contact"><label> <%= t('.address') %> </label></p> 
    <%= f.text_area :address, rows: 3, cols: 46, placeholder: t('.full_address')  %>


    <p class="contact"><label> <%= t('.pay_type') %> </label></p>
    <%= f.select :pay_type, Order::PAYMENT_TYPES, prompt: t('.payment_method') %>

    <br><br>
    <div style="margin-top:30px; padding-bottom:30px;">
      <%= f.submit t('.place_order'), class: 'btn btn-primary' %>
      <div style="float:right; margin-right: 20px"><%= link_to t('.back'), products_path, class: 'btn btn-success' %></div>
    </div>
  <% end %>

</div>      
</div>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1 style = "padding-top: 60px; padding-left: 600px;">Listing Orders</h1>
  <div class="container" style = "padding-left: 200px;">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Email</th>
        <th>Time</th>
        <th>Pay type</th>
      </tr>
    </thead>
    <tbody>
     <% @orders.each do |order| %>
      <tr>
        <td><%=order.name %></td>
        <td><%=order.address %></td>
        <td><%=order.email %></td>
        <td><%=order.created_at %></td>
        <td><%=order.pay_type %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
  

app/views/orders/new.html.erb
<div class="container-fluid" >
    <div class="container">
        <%= render 'form' %>
    </div>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @order.pay_type %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>