config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'contacts/new'

  get 'contacts/create'

  get 'application/privacy' => 'application#privacy'

  get 'application/about_us' => 'application#about_us'

  get 'user/new' => 'users#new'

  get 'user/show' => 'users#show'

  post 'user/new' => 'users#create'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'
  
  get '/logout' => 'sessions#destroy'

  get 'bills/show', as: :credit_bill  

  get 'bills/index', as: :bills   

  post 'likes/create', as: :like 

  scope '(:locale)' do 
    resources :products do  
    resources :comments 
      end
    resources :orders
    resources :contacts
    resources :line_items
    resources :carts
    root 'products#index', as: 'Products', via: :all
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	has_one :user

	def add_product(product_id)
		# current_item = line_items.find_by(product_id: product_id)
		current_item = nil
        line_items.each { |item| current_item = item if item.product_id == product_id } 
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end

	def total_price
  		line_items.to_a.sum { |item| item.total_price}
 	end
end

app/models/comment.rb
 class Comment < ActiveRecord::Base
   belongs_to :product
   belongs_to :user
 end 

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, :email, :message, presence: true

end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/line_item.rb
 class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
  	product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
 has_many :line_items, dependent: :destroy
 
 PAYMENT_TYPES = [ "Check", "Credit card", "Purchase Order"]
 
 validates :name, :address, :email, presence: true
 validates :pay_type, inclusion: PAYMENT_TYPES

 def add_line_items_from_cart(cart)
	cart.line_items.each do |item|	
	   item.cart_id = nil
	   line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :comments
  has_one :like
  before_destroy :ensure_no_referenced_by_any_line_item
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, :isbn, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

  def self.latest
    Product.order(:updated_at).last
  end

  def self.search(search)
    where("title LIKE ?", "%#{search}%") 
  end

  def self.search_by_category(search)
     where("category LIKE ?", "%#{search}%") 
  end

  private

  def ensure_no_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :cart
  has_many :comments
  has_one :like
  has_secure_password 
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
 	include CurrentCart
	
  def index
   	@order = Order.find(params[:id])
   end

   def show 
   	 @order = Order.find(params[:id])
   end
 end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == current_user.cart_id
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to acess invalid cart #{params[:id]}"
      redirect_to products_url, notice: 'Invalid cart'
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
    @product = Product.find(params[:product_id])

  	@like = Like.create(status: true, product_id: @product.id, user_id: current_user.id)
  	@product.likes_count += 1
  	@product.save


  	if @like.save
  		redirect_to @product
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper

end

app/helpers/carts_helper.rb
module CartsHelper
	def format_qty_value(number)
		number = number.to_i
		pluralize(number, 'item')
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def liked(id_param, product_id)
    if Like.find_by_user_id_and_product_id(id_param, product_id).nil? 
      false
    else
      Like.find_by_user_id_and_product_id(id_param, product_id).user_id == current_user.id 
    end    
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart.html.erb
<div class="container" style = "padding-bottom: 100px">
    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th style = "padding-right: 400px"><%= t('.product') %></th>
                        <th style = "float:left; padding-right: 40px;"><%= t('.quantity') %></th>
                        <th style = "padding-left: 50px; padding-right: 80px; float: left;"> <%= t('.price') %></th>
                        <th style = "float: left"><%= t('.total') %></th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody>
			            <%= render(@cart.line_items) %>
                        <td>   </td>
                        <td style = "font-size: 25px; float: left; padding-right: 170px;"><h1><%= t('.total2') %></h1></td>
                        <td style = "float: left; font-size: 25px"><h5><strong><%= number_to_currency(@cart.total_price) %></strong></h5></td>
                    <!-- <tr> <td></td><td></td><td></td> </tr>                     -->
                    <tr style = " border-top:2px solid rgb(97, 87, 87)">
                        <td>
	  					<%= button_to  t('.continue_shopping') , products_path, method: :get, class: 'btn btn-primary'%>
                        </td>
                        <td>
	  				    <%= button_to  t('.checkout') , new_order_path, method: :get, id: 'checkout', class: 'btn btn-success'%>
                       </td>
                       <td> 
                            <%= button_to  t('.empty_cart') , @cart, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger"%>
                       </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render(@cart) %>