config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'contacts/new'

  get 'contacts/create'

  get 'application/privacy' => 'application#privacy'

  get 'application/about_us' => 'application#about_us'

  get 'user/new' => 'users#new'

  get 'user/show' => 'users#show'

  post 'user/new' => 'users#create'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'
  
  get '/logout' => 'sessions#destroy'

  get 'bills/show', as: :credit_bill  

  get 'bills/index', as: :bills   

  post 'likes/create', as: :like 

  scope '(:locale)' do 
    resources :products do  
    resources :comments 
      end
    resources :orders
    resources :contacts
    resources :line_items
    resources :carts
    root 'products#index', as: 'Products', via: :all
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	has_one :user

	def add_product(product_id)
		# current_item = line_items.find_by(product_id: product_id)
		current_item = nil
        line_items.each { |item| current_item = item if item.product_id == product_id } 
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end

	def total_price
  		line_items.to_a.sum { |item| item.total_price}
 	end
end

app/models/comment.rb
 class Comment < ActiveRecord::Base
   belongs_to :product
   belongs_to :user
 end 

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, :email, :message, presence: true

end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/line_item.rb
 class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
  	product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
 has_many :line_items, dependent: :destroy
 
 PAYMENT_TYPES = [ "Check", "Credit card", "Purchase Order"]
 
 validates :name, :address, :email, presence: true
 validates :pay_type, inclusion: PAYMENT_TYPES

 def add_line_items_from_cart(cart)
	cart.line_items.each do |item|	
	   item.cart_id = nil
	   line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :comments
  has_one :like
  before_destroy :ensure_no_referenced_by_any_line_item
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, :isbn, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

  def self.latest
    Product.order(:updated_at).last
  end

  def self.search(search)
    where("title LIKE ?", "%#{search}%") 
  end

  def self.search_by_category(search)
     where("category LIKE ?", "%#{search}%") 
  end

  private

  def ensure_no_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :cart
  has_many :comments
  has_one :like
  has_secure_password 
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
 	include CurrentCart
	
  def index
   	@order = Order.find(params[:id])
   end

   def show 
   	 @order = Order.find(params[:id])
   end
 end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == current_user.cart_id
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to acess invalid cart #{params[:id]}"
      redirect_to products_url, notice: 'Invalid cart'
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
	include CurrentCart
	before_action :set_cart, only: [:create, :destroy]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
  	product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart  }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to @cart }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product, :cart_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper

end

app/helpers/carts_helper.rb
module CartsHelper
	def format_qty_value(number)
		number = number.to_i
		pluralize(number, 'item')
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def liked(id_param, product_id)
    if Like.find_by_user_id_and_product_id(id_param, product_id).nil? 
      false
    else
      Like.find_by_user_id_and_product_id(id_param, product_id).user_id == current_user.id 
    end    
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr>
   <td>
    <div class="media">
      <a class="thumbnail pull-left" href="#"> 
        <%= link_to image_tag(line_item.product.image_url, style: "width: 72px; height: 72px; float:left") %>
      </a>
      <div class="media-body" style = "padding-left:20px" >
        <h4 class="media-heading"><%= link_to line_item.product.title, products_path(line_item.product) %></h4>
        <h5 class="media-heading"> by <%= link_to line_item.product.author, products_path(line_item.product) %></h5>
      </div>
    </div>
  </td>
  <td style = "float:left;">
    <p class="card-title"><%= format_qty_value(line_item.quantity) %></p>
  </td>
  <td style = "float: left; padding-left: 80px;">
    <strong class="card-title"><%= number_to_currency(line_item.product.price) %></strong>
  </td>
  <td  style = "float: left; padding-left: 70px;">
   <strong class="card-title"><%= number_to_currency(line_item.total_price) %></strong>
 </td>
 <td>
      <%= button_to t('.remove'), line_item, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-link"%>
</td>
</tr>

app/views/line_items/create.js.erb
$('.add-to-cart').html("<%= escape_javascript render(@cart) %>");

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>