config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'contacts/new'

  get 'contacts/create'

  get 'application/privacy' => 'application#privacy'

  get 'application/about_us' => 'application#about_us'

  get 'user/new' => 'users#new'

  get 'user/show' => 'users#show'

  post 'user/new' => 'users#create'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'
  
  get '/logout' => 'sessions#destroy'

  get 'bills/show', as: :credit_bill  

  get 'bills/index', as: :bills   

  post 'likes/create', as: :like 

  scope '(:locale)' do 
    resources :products do  
    resources :comments 
      end
    resources :orders
    resources :contacts
    resources :line_items
    resources :carts
    root 'products#index', as: 'Products', via: :all
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	has_one :user

	def add_product(product_id)
		# current_item = line_items.find_by(product_id: product_id)
		current_item = nil
        line_items.each { |item| current_item = item if item.product_id == product_id } 
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end

	def total_price
  		line_items.to_a.sum { |item| item.total_price}
 	end
end

app/models/comment.rb
 class Comment < ActiveRecord::Base
   belongs_to :product
   belongs_to :user
 end 

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, :email, :message, presence: true

end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/line_item.rb
 class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
  	product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
 has_many :line_items, dependent: :destroy
 
 PAYMENT_TYPES = [ "Check", "Credit card", "Purchase Order"]
 
 validates :name, :address, :email, presence: true
 validates :pay_type, inclusion: PAYMENT_TYPES

 def add_line_items_from_cart(cart)
	cart.line_items.each do |item|	
	   item.cart_id = nil
	   line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :comments
  has_one :like
  before_destroy :ensure_no_referenced_by_any_line_item
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, :isbn, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

  def self.latest
    Product.order(:updated_at).last
  end

  def self.search(search)
    where("title LIKE ?", "%#{search}%") 
  end

  def self.search_by_category(search)
     where("category LIKE ?", "%#{search}%") 
  end

  private

  def ensure_no_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :cart
  has_many :comments
  has_one :like
  has_secure_password 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper

end

app/helpers/carts_helper.rb
module CartsHelper
	def format_qty_value(number)
		number = number.to_i
		pluralize(number, 'item')
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def liked(id_param, product_id)
    if Like.find_by_user_id_and_product_id(id_param, product_id).nil? 
      false
    else
      Like.find_by_user_id_and_product_id(id_param, product_id).user_id == current_user.id 
    end    
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book a book</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
	<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="icon" type="image/png" href= <%= image_url 'logo.png' %> >
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "body2">
	<div class="header-top">
	   <div class="wrap"> 
			  <div class="header-top-left">
				   
				   <div class="box">
						  <%= form_tag products_path class: 'box' do %>
						  	  	<%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), class: "dropdown", tabindex: "4", style: "background-color: #4CB1CA",
						  	onchange: 'this.form.submit()' %>
						  <% end %>
					</div>
					
					<div class="clear"></div>
			 </div>
			 <div class="cssmenu">
				<ul>
					<% if current_user %>
						<li><%= link_to t('.account'), user_show_path(name: current_user.name) %></li> |
						<li><%= link_to t('.log_out'), logout_path %></li> |
					<% else %>
						<li><%= link_to t('.log_in'), login_path %></li> |
						<li><%= link_to t('.sign_up'), user_new_path %></li> |
					<% end %>
				</ul>
			</div>
			<div class="clear"></div>
		</div>
	</div>

	<div class="header-bottom">
		<div class="wrap">
			<div class="header-bottom-left">
				<div class="logo">
					<%=link_to image_tag("logo.png"), products_path %>
				</div>
				<div class="menu">
				<ul class="megamenu skyblue">
				<li class="active grid"><%=link_to t('.home'), products_path %></li>
				<li style = "float:left;">  
					<div class="dropdown">
					    <button class="btn btn-default" type="button"  data-toggle="dropdown"> <%= t('.category') %> <span class="caret"></span> </button>
					    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
					      <li role="presentation">
					      	 <%= link_to t('.tekno'), products_path(:category => 'Technology')%>
					       </li>
					      <li role="presentation">
					      	 <%= link_to t('.business'), products_path(:category => 'Business') %>
					      </li>
					      <li role="presentation">
					      	 <%= link_to t('.history'), products_path(:category => 'History') %>
					      </li>
					    </ul>
  					</div> 		
				</li>
							
				<li>
			       <%= link_to t('.other'), products_path(:category => 'other'), style: "margin-left:20px" %></li>
				</li>
			</ul>
			</div>
		</div>
	   <div class="header-bottom-right">
		 <div class="search">	  
			<form action="" >
				<input type="text" name="search" class="textbox" class="form-control" value= <%= t(".search") %> name="search" id="search" onfocus="this.value = '';" >
				<%= submit_tag "Search" %>
				<div id="response"> </div>
			</form>
		 </div>
	  <div class="tag-list">
		<ul class="icon1 sub-icon1 profile_img">
			<li>
			<% if current_user %> 
					<%=link_to '', cart_path(current_user.cart_id), :class => "active-icon c2" if current_user.cart_id%>
			<% end %>
			</li> 
		</ul>
	  </div>
	 </div>
	</div>
	</div>
	<%= yield %>
</div>
 <div class="footer-bottom">
		 <div class="wrap">
			 <div class="copy">
				   <p>&copy <%=Time.now.year  %>  BOOK A BOOK | All Rights Reserved. </p>
			 </div>
			  <div class="f-list2">
				 <ul>
					<li><%= link_to t('.about_us'), application_about_us_path %></li>
					<li><%= link_to t('.contact'), new_contact_path %></li>
					<li><%= link_to t('.privacy'), application_privacy_path %></li>
				 </ul>
			  </div>
			  <div class="clear"></div>
		 </div>
  </div>
 </body>
</html>

app/views/order_notifier/received.html.erb
				<h3> <%= t('.babor') %> </h3>
				<p>
					<%= t('.this') %>
				</p>
				<table>
					<tr> <th colspan="2"><%= t('.books') %></th> <th><%= t('.price')%></th> </tr>
					<% total_price = 0 %> 
					<% @order.line_items.each do |line_item|%>
					<tr>	
						<td> <%= line_item.quantity %> &times; </td>
						<td> <%= line_item.product.title %> </td>
						<td> <%= number_to_currency(line_item.total_price) %> </td>
						<% total_price += line_item.total_price %>
					</tr>
					<% end %>
				</table> 
				
				<h3> <%= t('.tp') %> <%= number_to_currency(total_price) %> </h3>